---
apiVersion: v1
kind: Service
metadata:
  name: my-k8s-app-svc
spec:
  type: NodePort
  selector:
    app: my-k8s-app
  ports:
    - name: web
      nodePort: 30903
      port: 80
      targetPort: 80

