---
all:
  hosts:
    control-plane:
      ansible_host: 84.201.134.49
      ansible_user: ubuntu
    node-1:
      ansible_host: 51.250.25.127
      ansible_user: ubuntu
    node-2:
      ansible_host: 51.250.44.19
      ansible_user: ubuntu
    node-3:
      ansible_host: 62.84.118.40
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        control-plane:
    kube_node:
      hosts:
        node-1:
        node-2:
        node-3:
    etcd:
      hosts:
        control-plane:
    k8s_cluster:
      vars:
        supplementary_addresses_in_ssl_keys: [84.201.134.49]
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
